---
title: "Readme"
output:
  rmdformats::readthedown:
    fig_height: 7
    fig_width: 7
    keep_md: yes
---

```{r echo=F, message=FALSE, warning=FALSE}
library(dplyr)
library(xts)
library(reshape2)
library(formattable)
library(kyoboLT)
library(knitr)

opts_chunk$set(fig.path='figure/', fig.align="center", message=FALSE, warning=FALSE)
```

# install `kyoboLT` package

```{r eval=F}
devtools::install_github("lovetoken/kyoboLT")
```

# Useful functions for time series data

## `Xday_returns()`

```{r}
index <- matrix(rnorm(60,1000, 8^2), 20, 3)
data <- xts(round(index, 1), as.Date(16001:16020)) # xts package for time series data
names(data) <- paste("Fund", 1:3, sep="_")
data

# basic 3 day returns
Xday_returns(data, Xday=3)
# calculation 3 day log returns
Xday_returns(data, Xday=3, log.returns = T)
```

## `assess_returns()`

```{r}
returns <- Xday_returns(data, Xday=3, log.returns = T)

assess_returns(returns, "mean")
assess_returns(returns, "sd")
assess_returns(returns, "S.R")
```

## `tmplot()`

```{r}
library("quantmod")
data <- getSymbols("^ks11", from=Sys.Date()-1000, to=Sys.Date(), auto.assign=F)

tmplot(data)
tm1plot(data, "KS11.Close")
```

## `mvp()`

```{r}
mvp(returns)
```

# etc functions

## `trim()`

```{r}
trim("  Wow!  ", method="trailing")
trim("  Wow!  ", method="leading")

"  Wow!  " %>% trim %>% trim(method="leading")
```
