---
title: "Readme"
output:
  rmdformats::readthedown:
    fig_height: 5
    fig_width: 6.5
    keep_md: yes
---

```{r echo=F, message=FALSE, warning=FALSE}
library(dplyr)
library(xts)
library(reshape2)
library(formattable)
library(knitr)
library(kyoboLT)

opts_chunk$set(fig.align="center", message=FALSE, warning=FALSE)
```

# install `kyoboLT` package

```{r eval=F}
devtools::install_github("lovetoken/kyoboLT")
```

# Useful functions for time series data

## `Xday_returns()`

```{r}
index <- matrix(rnorm(120, 1000, 10^2), 30, 4)
data <- xts(round(index, 1), as.Date(16001:16030)) # xts package for time series data
names(data) <- paste("Fund", 1:4, sep="_")
data

# basic 3 day returns
xdiff_returns(data, 3)
# calculation 3 day log returns
xdiff_returns(data, 3, log.returns = T)
# not omit about start time index
xdiff_returns(data, 3, start.omit = F)
```

## `assess_returns()`

```{r}
returns <- xdiff_returns(data, 1, log.returns = T)

assess_returns(returns, "mean")
assess_returns(returns, "sd")
assess_returns(returns, "S.R")
```

## `tmplot()`

```{r}
library("quantmod")
data <- getSymbols("^ks11", from=Sys.Date()-1000, to=Sys.Date(), auto.assign=F)

tmplot(data)
tm1plot(data, "KS11.Close")
```

## `efff()`

```{r}
set.seed(123)
index <- matrix(rnorm(4000, 1000, 10^2), 1000, 4)
data <- xts(round(index, 1), as.Date(16001:17000)) # xts package for time series data
names(data) <- paste("Fund", 1:4, sep="_")
returns <- xdiff_returns(data, 1)

efff(returns, rg = 0.01039)
```
